#!/bin/bash

##############################
## INSTALL PACKAGE MANAGERS ##
##############################

echo '✅ Install homebrew'
sudo rm -rf /usr/local/Cellar /usr/local/.git && brew cleanup
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"

echo '✅ Install Mac App Store cli'
brew install mas

# Symlink the Mackup config
ln -s $HOME/.dotfiles/macos/.mackup.cfg $HOME/.mackup.cfg

echo '✅ Install mackup'
brew install mackup

###############################
## INSTALL DEVELOPMENT TOOLS ##
###############################

echo '✅ Install iterm2'

brew install --cask iterm2

echo '✅ Install oh-my-zsh'
echo '-----------------'
rm -rf $HOME/.oh-my-zsh
curl -L https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
rm $HOME/.zshrc
ln -s $HOME/.dotfiles/shell/.zshrc $HOME/.zshrc
source $HOME/.zshrc

echo '✅ Install nvm'
brew install nvm
nvm install --lts

echo 'Configure npm'
# Create a directory for global packages and tell npm where to store globally installed packages
mkdir "${HOME}/.npm-packages"
npm config set prefix "${HOME}/.npm-packages"

echo '✅ Install wget'
brew install wget

echo '✅ Install ncdu'
echo '------------'
brew install ncdu

echo '✅ Install ack'
brew install ack

echo '✅ Install jq'
brew install jq

echo '✅ Install some nice quicklook plugins'
brew install --cask qlcolorcode qlstephen qlmarkdown quicklook-json qlprettypatch quicklook-csv

echo '✅ Install herd'
echo '------------'
brew install --cask herd

echo '✅ Install tinkerwell'
brew install --cask tinkerwell

echo '✅ Install helo'
brew install --cask helo

echo '✅ Install aicommits'
npm install -g aicommits

echo '✅ Install DBngin'
brew install --cask dbngin

echo '✅ Install yarn'
brew install yarn

echo '✅ Install memory (timely)'
brew install --cask memory

echo '✅ Install VScode'
brew install --cask visual-studio-code

echo '✅ Install raycast'
brew install --cask raycast

#
# echo '✅ Install fig'
#
# brew install --cask fig

echo '✅ Install github cli'
brew install gh

echo '✅ Install Ray'
brew install --cask ray

echo '✅ Install MySQL tools'
brew install mysql-client

##############################
## INSTALL GENERAL SOFTWARE ##
##############################

echo '✅ Install ghostscript'
brew install ghostscript

echo '✅ Install affinity photo'
brew install --cask affinity-photo

echo '✅ Install affinity designer'
brew install --cask affinity-designer

echo '✅ Install github desktop'
brew install --cask github

echo '✅ Install setapp'
brew install --cask setapp

echo '✅ Install missive'
brew install --cask missive

echo '✅ Install 1password'
brew install --cask 1password

echo '✅ Install discord'
brew install --cask discord

echo '✅ Install screenflow'
brew install --cask screenflow

echo '✅ Install Office'
brew install --cask microsoft-office

echo '✅ Install Google drive'
brew install --cask google-drive

echo '✅ Install google chrome'
brew install --cask google-chrome

# # echo '✅ Install figma'
# # brew install --cask figma

echo '✅ Install Notion'
brew install --cask notion

echo '✅ Install Facebook messenger'
brew install --cask messenger

echo '✅ Install spotify'
brew install --cask spotify

echo '✅ Install Microsoft Teams'
brew install --cask microsoft-teams

echo '✅ Install Handbrake'
brew install --cask handbrake

echo '✅ Install idrive'
brew install --cask idrive

echo '✅ Install anytype.io'
brew install --cask anytype

###############################
## INSTALL MAC STORE SHIZZLE ##
###############################

echo '✅ Install Mac App store apps'

mas install 1278508951 # trello
mas install 1444383602 # Good notes
mas install 975937182 # Fantastical
mas install 1575557335 # Kaleidoscope
#mas install 1091189122 # Bear
mas install 405772121 # LittleIpsum
# mas install 1491071483 # Tot
mas install 1398373917 # UpNote
mas install 585829637 # Todoist
mas install 310633997 # Whatsapp

###########################
## DO SOME GENERAL STUFF ##
###########################

# Hide "last login" line when starting a new terminal session
touch $HOME/.hushlogin

# Add global gitignore
ln -s $HOME/.dotfiles/shell/.global-gitignore $HOME/.global-gitignore
git config --global core.excludesfile $HOME/.global-gitignore

########################
## SETUP BASE SITES's ##
########################

echo '+++++++++++++++++++++++++++'
echo '++       All done!       ++'
echo '+++++++++++++++++++++++++++'
