#!/bin/bash

##############################
## INSTALL PACKAGE MANAGERS ##
##############################

echo '--'
echo 'Install homebrew'
echo '--'
echo install homebrew
sudo rm -rf /usr/local/Cellar /usr/local/.git && brew cleanup
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"

echo '--'
echo 'Install Mac App Store cli'
echo '--'
brew install mas

# Symlink the Mackup config
ln -s $HOME/.dotfiles/macos/.mackup.cfg $HOME/.mackup.cfg

echo '--'
echo 'Install mackup'
echo '--'
brew install mackup

###############################
## INSTALL DEVELOPMENT TOOLS ##
###############################

echo '--'
echo 'Install iterm2'
echo '--'

brew install --cask iterm2

echo 'Install oh-my-zsh'
echo '-----------------'
rm -rf $HOME/.oh-my-zsh
curl -L https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
rm $HOME/.zshrc
ln -s $HOME/.dotfiles/shell/.zshrc $HOME/.zshrc
source $HOME/.zshrc

echo '--'
echo 'Install nvm'
echo '--'
brew install nvm
nvm install --lts

echo '--'
echo 'Configure npm'
echo '--'
# Create a directory for global packages and tell npm where to store globally installed packages
mkdir "${HOME}/.npm-packages"
npm config set prefix "${HOME}/.npm-packages"

echo '--'
echo 'Install wget'
echo '--'
brew install wget

echo '--'
echo 'Install ncdu'
echo '------------'
brew install ncdu

echo '--'
echo 'Install ack'
echo '--'
brew install ack

echo '--'
echo 'Install jq'
echo '--'
brew install jq

echo '--'
echo 'Install some nice quicklook plugins'
echo '--'
brew install --cask qlcolorcode qlstephen qlmarkdown quicklook-json qlprettypatch quicklook-csv

echo '--'
echo 'Install herd'
echo '------------'
brew install --cask herd

echo '--'
echo 'Install tinkerwell'
echo '--'
brew install --cask tinkerwell

echo '--'
echo 'Install helo'
echo '--'
brew install --cask helo

echo '--'
echo 'Install aicommits'
echo '--'
npm install -g aicommits

echo '--'
echo 'Install DBngin'
echo '--'
brew install --cask dbngin

echo '--'
echo 'Install yarn'
echo '--'
brew install yarn

echo '--'
echo 'Install memory (timely)'
echo '--'
brew install --cask memory

echo '--'
echo 'Install VScode'
echo '--'
brew install --cask visual-studio-code

echo '--'
echo 'Install raycast'
echo '--'
brew install --cask raycast

# echo '--'
# echo 'Install fig'
# echo '--'
# brew install --cask fig

echo '--'
echo 'Install github cli'
echo '--'
brew install gh

echo '--'
echo 'Install Ray'
echo '--'
brew install --cask ray

echo '--'
echo 'Install MySQL tools'
echo '--'
brew install mysql-client

##############################
## INSTALL GENERAL SOFTWARE ##
##############################

echo 'Install ghostscript'
brew install ghostscript

echo 'Install affinity photo'
brew install --cask affinity-photo

echo 'Install affinity designer'
brew install --cask affinity-designer

echo 'Install github desktop'
brew install --cask github

echo 'Install setapp'
brew install --cask setapp

echo 'Install missive'
brew install --cask missive

echo 'Install 1password'
brew install --cask 1password

echo 'Install discord'
brew install --cask discord

echo 'Install screenflow'
brew install --cask screenflow

echo 'Install Office'
brew install --cask microsoft-office

echo 'Install Google drive'
brew install --cask google-drive

echo 'Install google chrome'
brew install --cask google-chrome

# # echo 'Install figma'
# # brew install --cask figma

echo 'Install Notion'
brew install --cask notion

echo 'Install Facebook messenger'
brew install --cask messenger

echo 'Install spotify'
brew install --cask spotify

echo 'Install Microsoft Teams'
brew install --cask microsoft-teams

echo 'Install Handbrake'
brew install --cask handbrake

###############################
## INSTALL MAC STORE SHIZZLE ##
###############################

echo '--'
echo 'Install Mac App store apps'
echo '--'

mas install 1278508951 # trello
mas install 1444383602 # Good notes
mas install 975937182 # Fantastical
mas install 1575557335 # Kaleidoscope
#mas install 1091189122 # Bear
mas install 405772121 # LittleIpsum
# mas install 1491071483 # Tot
mas install 1398373917 # UpNote
mas install 585829637 # Todoist
# mas install 1147396723 # Whatsapp (no silicon)

###########################
## DO SOME GENERAL STUFF ##
###########################

# Hide "last login" line when starting a new terminal session
touch $HOME/.hushlogin

# Add global gitignore
ln -s $HOME/.dotfiles/shell/.global-gitignore $HOME/.global-gitignore
git config --global core.excludesfile $HOME/.global-gitignore

########################
## SETUP BASE SITES's ##
########################

echo '+++++++++++++++++++++++++++'
echo '++       All done!       ++'
echo '+++++++++++++++++++++++++++'
