#!/bin/bash

# Hide "last login" line when starting a new terminal session
touch $HOME/.hushlogin

# Install zsh
echo 'Install oh-my-zsh'
echo '-----------------'
rm -rf $HOME/.oh-my-zsh
curl -L https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh

# Add global gitignore
ln -s $HOME/.dotfiles/shell/.global-gitignore $HOME/.global-gitignore
git config --global core.excludesfile $HOME/.global-gitignore

# Symlink zsh prefs
rm $HOME/.zshrc
ln -s $HOME/.dotfiles/shell/.zshrc $HOME/.zshrc

# Symlink the Mackup config
ln -s $HOME/.dotfiles/macos/.mackup.cfg $HOME/.mackup.cfg

echo 'Install homebrew'
echo '----------------'
echo install homebrew
sudo rm -rf /usr/local/Cellar /usr/local/.git && brew cleanup
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"

echo 'Install nvm'
echo '--'
brew install nvm

echo 'Configure npm'
echo '-------------'
# Create a directory for global packages and tell npm where to store globally installed packages
mkdir "${HOME}/.npm-packages"
npm config set prefix "${HOME}/.npm-packages"

echo 'Install wget'
echo '--'
brew install wget

echo 'Install ncdu'
echo '------------'
brew install ncdu

echo 'Install ack'
echo '--'
brew install ack

echo 'Install some nice quicklook plugins'
echo '--'
brew install --cask qlcolorcode qlstephen qlmarkdown quicklook-json qlprettypatch quicklook-csv

echo 'Install herd'
echo '------------'
brew install --cask herd

echo 'Install tinkerwell'
echo '--'
brew install --cask tinkerwell

echo 'Install helo'
echo '--'
brew install --cask helo

echo 'Install aicommits'
echo '--'
npm install -g aicommits

echo 'Install DBngin'
echo '--'
brew install --cask dbngin

echo 'Install yarn'
echo '--'
brew install yarn

echo 'Install ghostscript'
echo '--'
brew install ghostscript

echo 'Install mackup'
echo '--'
brew install mackup

echo 'Install zsh-autosuggestions'
echo '--'
brew install zsh-autosuggestions

echo 'Install affinity photo'
echo '--'
brew install --cask affinity-photo

echo 'Install affinity designer'
echo '--'
brew install --cask affinity-designer

echo 'Install setapp'
echo '--'
brew install --cask setapp

echo 'Install fantastical'
echo '--'
brew install --cask fantastical

echo 'Install missive'
echo '--'
brew install --cask missive

echo 'Install 1password'
echo '--'
brew install --cask 1password

echo 'Install discord'
echo '--'
brew install --cask discord

echo 'Install VScode'
echo '--'
brew install --cask visual-studio-code

echo 'Install raycast'
echo '--'
brew install --cask raycast

echo 'Install fig'
echo '--'
brew install --cask fig

echo 'Install screenflow'
echo '--'
brew install --cask screenflow

echo 'Install Office'
echo '--'
brew install --cask microsoft-office

echo 'Install Google drive'
echo '--'
brew install --cask google-drive

echo 'Install google chrome'
echo '--'
brew install --cask google-chrome

echo 'Install figma'
echo '--'
brew install --cask figma

echo 'Install github cli'
echo '--'
brew install gh

echo 'Install Ray'
echo '--'
brew install --cask ray

echo 'Install Fonts'
echo '--'
brew install --cask font-lato
brew install --cask font-open-sans
brew install --cask font-roboto
brew install --cask font-source-code-pro
brew install --cask font-source-sans-pro
brew install --cask font-source-serif-pro

echo 'Install Mac App Store cli'
echo '--'
brew install mas

echo 'Install Mac App store apps'
echo '--'
mas 'Trello', id: 1278508951
mas 'GoodNotes', id: 1444383602
mas 'Fantastical', id: 975937182
mas 'Kaleidoscope', id: 1575557335
mas 'Bear', id: 1091189122
mas 'LittleIpsum', id: 405772121
mas 'Tot', id: 1491071483
mas 'Todoist', id: 585829637
mas 'Whatsapp', id: 1147396723


echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
echo 'All done!'
echo 'Things to do to:'
echo '1. Install monalisa font included in ~/.dotfiles/misc'
echo '2. If you have not backed up via Mackup yet, then run `mackup backup` to symlink preferences for a wide collection of apps to your dropbox. If you already had a backup via mackup run `mackup restore` You will find more info on Mackup here: https://github.com/lra/mackup.'
echo '3. Set some sensible os x defaults by running: $HOME/.dotfiles/macos/set-defaults.sh'
echo '4. Make a .dotfiles-custom/shell/.aliases for your personal commands'

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
